import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));

const generatedFileComment = `
/**
 * This file is autogenerated from protocol sources.
 * You should not edit it manually or your changes might be overwritten.
 */`;

function evaluateSolidityUintExpression(expression) {
  const normalized = expression.replace(/\/\/.*$/gm, "").trim();
  const daysMatch = normalized.match(/^(\d+)\s+days$/);
  if (daysMatch) {
    return BigInt(daysMatch[1]) * 24n * 60n * 60n;
  }

  const powerMatch = normalized.match(/^(\d+)\s*\*\s*10\s*\*\*\s*(\d+)$/);
  if (powerMatch) {
    return BigInt(powerMatch[1]) * 10n ** BigInt(powerMatch[2]);
  }

  if (/^\d+$/.test(normalized)) {
    return BigInt(normalized);
  }

  throw new Error(`Unsupported ProtocolLib constant expression: ${expression}`);
}

function parseProtocolLibConstants() {
  const librariesPath = join(__dirname, "..", "contracts", "Libraries.sol");
  const source = readFileSync(librariesPath, "utf8");
  const protocolLibMatch = source.match(
    /library\s+ProtocolLib\s*{([\s\S]*?)\n}/
  );

  if (!protocolLibMatch) {
    throw new Error("Could not find ProtocolLib in contracts/Libraries.sol");
  }

  const constants = {};
  const constantRegex =
    /uint256\s+internal\s+constant\s+([A-Z0-9_]+)\s*=\s*([^;]+);/g;
  let match;

  while ((match = constantRegex.exec(protocolLibMatch[1])) !== null) {
    constants[match[1]] = evaluateSolidityUintExpression(match[2]);
  }

  return constants;
}

function requireProtocolConstants(constants, names) {
  for (const constantName of names) {
    if (constants[constantName] === undefined) {
      throw new Error(`Missing ProtocolLib constant: ${constantName}`);
    }
  }
}

function generateProtocolConstantsFile() {
  const constants = parseProtocolLibConstants();
  requireProtocolConstants(constants, [
    "BENCHMARK_YIELD_BP",
    "PROTOCOL_FEE_BP",
    "EARLY_SALE_PENALTY_BP",
    "DEPRECIATION_RATE_BP",
    "MIN_PROTOCOL_FEE",
    "MIN_EARLY_SALE_PENALTY",
  ]);

  return `
    ${generatedFileComment}

    import { BP_PRECISION, SECONDS_PER_YEAR } from "~~/config/units";

    export const PROTOCOL_BENCHMARK_YIELD_BP = ${constants.BENCHMARK_YIELD_BP}n;
    export const PROTOCOL_FEE_BP = ${constants.PROTOCOL_FEE_BP}n;
    export const PROTOCOL_EARLY_SALE_PENALTY_BP = ${constants.EARLY_SALE_PENALTY_BP}n;
    export const PROTOCOL_DEPRECIATION_RATE_BP = ${constants.DEPRECIATION_RATE_BP}n;
    export const PROTOCOL_MIN_PROTOCOL_FEE = ${constants.MIN_PROTOCOL_FEE}n;
    export const PROTOCOL_MIN_EARLY_SALE_PENALTY = ${constants.MIN_EARLY_SALE_PENALTY}n;

    export const calculateProtocolEarnings = (principal: bigint, timeElapsed: bigint, earningsBP: bigint) => {
      return (principal * timeElapsed * earningsBP) / (SECONDS_PER_YEAR * BP_PRECISION);
    };

    export const calculateProtocolFee = (amount: bigint) => {
      if (amount === 0n) return 0n;
      const fee = (amount * PROTOCOL_FEE_BP) / BP_PRECISION;
      return fee < PROTOCOL_MIN_PROTOCOL_FEE ? PROTOCOL_MIN_PROTOCOL_FEE : fee;
    };
  `;
}

function generateProtocolDeploymentsFile() {
  const networksPath = join(__dirname, "..", "subgraph", "networks.json");
  const networks = JSON.parse(readFileSync(networksPath, "utf8"));
  const networkNameByChainId = {
    31337: "localhost",
    10143: "monad-testnet",
    421614: "arbitrum-sepolia",
    80002: "polygon-amoy",
    11155111: "sepolia",
  };

  const startBlocksByChainId = {};
  for (const [chainId, networkName] of Object.entries(networkNameByChainId)) {
    const networkConfig = networks[networkName];
    if (!networkConfig) continue;

    startBlocksByChainId[chainId] = Object.fromEntries(
      Object.entries(networkConfig)
        .filter(([, contractConfig]) =>
          Number.isInteger(contractConfig?.startBlock)
        )
        .map(([contractName, contractConfig]) => [
          contractName,
          contractConfig.startBlock,
        ])
    );
  }

  return `
    ${generatedFileComment}

    export const PROTOCOL_CONTRACT_START_BLOCKS_BY_CHAIN_ID = ${JSON.stringify(
      startBlocksByChainId,
      null,
      2
    )} as const;

    export const getProtocolContractStartBlock = (chainId: number, contractName: string): bigint | undefined => {
      const chainStartBlocks = PROTOCOL_CONTRACT_START_BLOCKS_BY_CHAIN_ID[
        String(chainId) as keyof typeof PROTOCOL_CONTRACT_START_BLOCKS_BY_CHAIN_ID
      ] as Record<string, number> | undefined;
      const startBlock = chainStartBlocks?.[contractName];

      return typeof startBlock === "number" && Number.isInteger(startBlock) ? BigInt(startBlock) : undefined;
    };
  `;
}

function main() {
  const targetDir = join(__dirname, "..", "..", "..", "web", "config");
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }

  writeFileSync(
    join(targetDir, "protocol.ts"),
    format(generateProtocolConstantsFile(), { parser: "typescript" })
  );
  writeFileSync(
    join(targetDir, "protocolDeployments.ts"),
    format(generateProtocolDeploymentsFile(), { parser: "typescript" })
  );

  console.log(`📝 Updated frontend protocol config files on ${targetDir}`);
}

try {
  main();
} catch (error) {
  console.error("Error:", error);
  process.exitCode = 1;
}
