/**
 * This file is autogenerated from protocol sources.
 * You should not edit it manually or your changes might be overwritten.
 */
import { BP_PRECISION, SECONDS_PER_YEAR } from "~~/config/units";

export const PROTOCOL_BENCHMARK_YIELD_BP = 1000n;
export const PROTOCOL_FEE_BP = 250n;
export const PROTOCOL_EARLY_SALE_PENALTY_BP = 500n;
export const PROTOCOL_DEPRECIATION_RATE_BP = 1200n;
export const PROTOCOL_MIN_PROTOCOL_FEE = 1000000n;
export const PROTOCOL_MIN_EARLY_SALE_PENALTY = 1000000n;

export const calculateProtocolEarnings = (principal: bigint, timeElapsed: bigint, earningsBP: bigint) => {
  return (principal * timeElapsed * earningsBP) / (SECONDS_PER_YEAR * BP_PRECISION);
};

export const calculateProtocolFee = (amount: bigint) => {
  if (amount === 0n) return 0n;
  const fee = (amount * PROTOCOL_FEE_BP) / BP_PRECISION;
  return fee < PROTOCOL_MIN_PROTOCOL_FEE ? PROTOCOL_MIN_PROTOCOL_FEE : fee;
};
