/**
 * This file is autogenerated from protocol sources.
 * You should not edit it manually or your changes might be overwritten.
 */

export const PROTOCOL_CONTRACT_START_BLOCKS_BY_CHAIN_ID = {
  "10143": {
    MockUSDC: 36027040,
    RoboshareTokens: 36027053,
    PartnerManager: 36027061,
    RegistryRouter: 36027071,
    VehicleRegistry: 36027080,
    Treasury: 36027088,
    EarningsManager: 36027098,
    Marketplace: 36027107,
    PositionManager: 36027116,
  },
  "31337": {
    MockUSDC: 0,
    RoboshareTokens: 0,
    PartnerManager: 0,
    RegistryRouter: 0,
    VehicleRegistry: 0,
    Treasury: 0,
    EarningsManager: 0,
    Marketplace: 0,
  },
  "80002": {
    MockUSDC: 39639887,
    RoboshareTokens: 39639894,
    PartnerManager: 39639897,
    RegistryRouter: 39639900,
    VehicleRegistry: 39639904,
    Treasury: 39639908,
    EarningsManager: 39639912,
    Marketplace: 39639917,
    PositionManager: 39639920,
  },
  "421614": {
    MockUSDC: 273622759,
    RoboshareTokens: 273622765,
    PartnerManager: 273622768,
    RegistryRouter: 273622772,
    VehicleRegistry: 273622775,
    Treasury: 273622779,
    EarningsManager: 273622781,
    Marketplace: 273622784,
    PositionManager: 273622788,
  },
  "11155111": {
    MockUSDC: 10555421,
    RoboshareTokens: 10555424,
    PartnerManager: 10555426,
    RegistryRouter: 10555428,
    VehicleRegistry: 10555430,
    Treasury: 10555432,
    EarningsManager: 10555434,
    Marketplace: 10555436,
  },
} as const;

export const getProtocolContractStartBlock = (chainId: number, contractName: string): bigint | undefined => {
  const chainStartBlocks = PROTOCOL_CONTRACT_START_BLOCKS_BY_CHAIN_ID[
    String(chainId) as keyof typeof PROTOCOL_CONTRACT_START_BLOCKS_BY_CHAIN_ID
  ] as Record<string, number> | undefined;
  const startBlock = chainStartBlocks?.[contractName];

  return typeof startBlock === "number" && Number.isInteger(startBlock) ? BigInt(startBlock) : undefined;
};
